SET session_replication_role = 'replica';


TRUNCATE TABLE "UserInfo" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Users" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Like" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Comment" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PetterImagesTimeline" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "petter_infos" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "petter_images" RESTART IDENTITY CASCADE;


SET session_replication_role = 'origin';

SELECT tablename
FROM pg_tables
WHERE schemaname = 'public';